package com.graduation.foodsystem.model;

public class Evaluate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_id
     *
     * @mbg.generated
     */
    private Integer evaluateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.evaluate_detail
     *
     * @mbg.generated
     */
    private String evaluateDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evaluate.isdelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_id
     *
     * @return the value of evaluate.evaluate_id
     *
     * @mbg.generated
     */
    public Integer getEvaluateId() {
        return evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_id
     *
     * @param evaluateId the value for evaluate.evaluate_id
     *
     * @mbg.generated
     */
    public void setEvaluateId(Integer evaluateId) {
        this.evaluateId = evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.evaluate_detail
     *
     * @return the value of evaluate.evaluate_detail
     *
     * @mbg.generated
     */
    public String getEvaluateDetail() {
        return evaluateDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.evaluate_detail
     *
     * @param evaluateDetail the value for evaluate.evaluate_detail
     *
     * @mbg.generated
     */
    public void setEvaluateDetail(String evaluateDetail) {
        this.evaluateDetail = evaluateDetail == null ? null : evaluateDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.user_id
     *
     * @return the value of evaluate.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.user_id
     *
     * @param userId the value for evaluate.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.order_id
     *
     * @return the value of evaluate.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.order_id
     *
     * @param orderId the value for evaluate.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evaluate.isdelete
     *
     * @return the value of evaluate.isdelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evaluate.isdelete
     *
     * @param isdelete the value for evaluate.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}