package com.graduation.foodsystem.model;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_id
     *
     * @mbg.generated
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_type
     *
     * @mbg.generated
     */
    private String imageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.image_from
     *
     * @mbg.generated
     */
    private String imageFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.object_id
     *
     * @mbg.generated
     */
    private Integer objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.isdelete
     *
     * @mbg.generated
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_id
     *
     * @return the value of image.image_id
     *
     * @mbg.generated
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_id
     *
     * @param imageId the value for image.image_id
     *
     * @mbg.generated
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_type
     *
     * @return the value of image.image_type
     *
     * @mbg.generated
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_type
     *
     * @param imageType the value for image.image_type
     *
     * @mbg.generated
     */
    public void setImageType(String imageType) {
        this.imageType = imageType == null ? null : imageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_url
     *
     * @return the value of image.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_url
     *
     * @param imageUrl the value for image.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.image_from
     *
     * @return the value of image.image_from
     *
     * @mbg.generated
     */
    public String getImageFrom() {
        return imageFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.image_from
     *
     * @param imageFrom the value for image.image_from
     *
     * @mbg.generated
     */
    public void setImageFrom(String imageFrom) {
        this.imageFrom = imageFrom == null ? null : imageFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.object_id
     *
     * @return the value of image.object_id
     *
     * @mbg.generated
     */
    public Integer getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.object_id
     *
     * @param objectId the value for image.object_id
     *
     * @mbg.generated
     */
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.isdelete
     *
     * @return the value of image.isdelete
     *
     * @mbg.generated
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.isdelete
     *
     * @param isdelete the value for image.isdelete
     *
     * @mbg.generated
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}