package com.graduation.foodsystem.model;

public class OrderProductRef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product_ref.ref_id
     *
     * @mbg.generated
     */
    private Integer refId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product_ref.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_product_ref.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product_ref.ref_id
     *
     * @return the value of order_product_ref.ref_id
     *
     * @mbg.generated
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product_ref.ref_id
     *
     * @param refId the value for order_product_ref.ref_id
     *
     * @mbg.generated
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product_ref.order_id
     *
     * @return the value of order_product_ref.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product_ref.order_id
     *
     * @param orderId the value for order_product_ref.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_product_ref.product_id
     *
     * @return the value of order_product_ref.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_product_ref.product_id
     *
     * @param productId the value for order_product_ref.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}