package com.graduation.foodsystem.mapper;

import com.graduation.foodsystem.model.Evaluate;
import io.swagger.models.auth.In;

import java.util.List;

public interface EvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer evaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated
     */
    int insert(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated
     */
    int insertSelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated
     */
    Evaluate selectByPrimaryKey(Integer evaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Evaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evaluate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Evaluate record);

    Evaluate selectByOrderId(Integer orderId);

    int deleteByEvaluateId(Integer evaluateId);

    List<Evaluate> selectByUserId(Integer userId);
}