package com.graduation.foodsystem.mapper;

import com.graduation.foodsystem.model.Market;

import java.util.List;

public interface MarketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer marketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated
     */
    int insert(Market record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated
     */
    int insertSelective(Market record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated
     */
    Market selectByPrimaryKey(Integer marketId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Market record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table market
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Market record);

    Market selectByUserId();

    List<Market> selectAll();
}