package com.graduation.foodsystem.mapper;

import com.graduation.foodsystem.model.OrderProductRef;
import com.graduation.foodsystem.model.Product;

import java.util.List;

public interface OrderProductRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product_ref
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product_ref
     *
     * @mbg.generated
     */
    int insert(OrderProductRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product_ref
     *
     * @mbg.generated
     */
    int insertSelective(OrderProductRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product_ref
     *
     * @mbg.generated
     */
    OrderProductRef selectByPrimaryKey(Integer refId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product_ref
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderProductRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_product_ref
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderProductRef record);

    //通过orderId获得所有的product
    List<OrderProductRef> selectByOrderId(Integer orderId);
}